# Generated by Django 5.0.2 on 2024-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='usersmodel',
            table='users',
        ),
    ]
