# Generated by Django 5.0.2 on 2024-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmodel_user_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmodel',
            table='chat',
        ),
    ]
